name: unit tests
on: [push]

jobs:
  run-unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: latest
          clj-kondo: latest
      - uses: actions/cache@v3
        env:
          cache-name: maven-cache
        with:
          path: ~/.m2
          key: ${{ runner.os }}-test-${{ env.cache-name }}-${{ hashFiles('**/deps.edn') }}
      - run: script/test
